#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  controller: App\Controller\HomeController::index

app_produit:
  path: /produits
  controller: App\Controller\ProduitController::allProduits
